// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AiConversationMessage struct {
	ID        uuid.UUID
	SessionID uuid.UUID
	Role      string
	Content   string
	Metadata  json.RawMessage
	CreatedAt time.Time
}

type AiConversationSession struct {
	ID         uuid.UUID
	CompanyID  uuid.UUID
	UserID     uuid.UUID
	ProviderID string
	Title      sql.NullString
	Metadata   json.RawMessage
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type AiDocumentJob struct {
	ID           uuid.UUID
	CompanyID    uuid.UUID
	UserID       uuid.UUID
	ProviderID   string
	Status       string
	Request      json.RawMessage
	Response     pqtype.NullRawMessage
	ErrorMessage sql.NullString
	CreatedAt    time.Time
	UpdatedAt    time.Time
	CompletedAt  sql.NullTime
}

type AiProviderCredential struct {
	ID               uuid.UUID
	CompanyID        uuid.UUID
	UserID           uuid.NullUUID
	ProviderID       string
	CredentialCipher []byte
	CredentialHash   []byte
	Metadata         json.RawMessage
	CreatedAt        time.Time
	UpdatedAt        time.Time
	LastUsedAt       sql.NullTime
	RotatedAt        sql.NullTime
	Label            sql.NullString
	IsDefault        bool
	LastTestedAt     sql.NullTime
	Fingerprint      sql.NullString
}

type AiProviderCredentialEvent struct {
	ID               uuid.UUID
	CompanyID        uuid.UUID
	UserID           uuid.NullUUID
	ActorUserID      uuid.NullUUID
	ProviderID       string
	Action           string
	MetadataSnapshot json.RawMessage
	CreatedAt        time.Time
}

type AiToolInvocation struct {
	ID           uuid.UUID
	UserID       uuid.NullUUID
	ProviderID   string
	ToolName     string
	Status       string
	Request      pqtype.NullRawMessage
	Response     pqtype.NullRawMessage
	ErrorMessage sql.NullString
	CreatedAt    time.Time
}

type AiUserPreference struct {
	UserID     uuid.UUID
	CompanyID  uuid.UUID
	ProviderID string
	Model      sql.NullString
	Metadata   json.RawMessage
	UpdatedAt  time.Time
}

type Bundle struct {
	ID         uuid.UUID
	BundleName string
	IsActive   bool
	CompanyID  uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type BundlePerformanceObligation struct {
	BundleID                 uuid.UUID
	PerformanceObligationsID uuid.UUID
}

type BundleProduct struct {
	BundleID  uuid.UUID
	ProductID uuid.UUID
	CompanyID uuid.UUID
}

type Company struct {
	ID          uuid.UUID
	CompanyName string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	IsActive    bool
}

type Contract struct {
	ID          uuid.UUID
	CompanyID   uuid.UUID
	CustomerID  uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	StartDate   time.Time
	EndDate     time.Time
	IsFinal     bool
	ContractUrl sql.NullString
}

type Customer struct {
	ID           uuid.UUID
	CustomerName string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	IsActive     bool
	CompanyID    uuid.UUID
}

type PerformanceObligation struct {
	ID                         uuid.UUID
	PerformanceObligationsName string
	ContractID                 uuid.UUID
	CreatedAt                  time.Time
	UpdatedAt                  time.Time
	StartDate                  time.Time
	EndDate                    time.Time
	FunctionalCurrency         string
	Discount                   string
	TransactionPrice           int64
}

type Product struct {
	ID                              uuid.UUID
	ProdName                        string
	RevAssessment                   string
	OverTimePercent                 string
	PointInTimePercent              string
	StandaloneSellingPriceMethod    string
	StandaloneSellingPricePriceHigh string
	StandaloneSellingPricePriceLow  string
	CompanyID                       uuid.UUID
	IsActive                        bool
	DefaultCurrency                 string
	CreatedAt                       time.Time
	UpdatedAt                       time.Time
}

type ProductPerformanceObligation struct {
	ProductID                uuid.UUID
	PerformanceObligationsID uuid.UUID
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	IssuedIp  pqtype.Inet
	UserAgent sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	CompanyID    uuid.UUID
	Email        string
	PasswordHash string
	IsActive     bool
}
