// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (Company_ID, Email, Password_Hash)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, created_at, updated_at, company_id, email, password_hash, is_active
`

type CreateUserParams struct {
	CompanyID    uuid.UUID
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.CompanyID, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE ID = $1
AND Company_ID = $2
`

type DeleteUserParams struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteUser, arg.ID, arg.CompanyID)
	return err
}

const getActiveUsersCompany = `-- name: GetActiveUsersCompany :many
SELECT id, created_at, updated_at, company_id, email, password_hash, is_active FROM users
WHERE Company_ID = $1
AND Is_Active = TRUE
`

func (q *Queries) GetActiveUsersCompany(ctx context.Context, companyID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getActiveUsersCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyID,
			&i.Email,
			&i.PasswordHash,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, created_at, updated_at, company_id, email, password_hash, is_active FROM users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyID,
			&i.Email,
			&i.PasswordHash,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllUsersCompany = `-- name: GetAllUsersCompany :many
SELECT id, created_at, updated_at, company_id, email, password_hash, is_active FROM users
WHERE Company_ID = $1
`

func (q *Queries) GetAllUsersCompany(ctx context.Context, companyID uuid.UUID) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsersCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyID,
			&i.Email,
			&i.PasswordHash,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, updated_at, company_id, email, password_hash, is_active FROM users
WHERE ID = $1
AND Company_ID = $2
`

type GetUserParams struct {
	ID        uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, arg.ID, arg.CompanyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, company_id, email, password_hash, is_active FROM users
WHERE Company_ID = $1
AND Email = $2
`

type GetUserByEmailParams struct {
	CompanyID uuid.UUID
	Email     string
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, arg.CompanyID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
	)
	return i, err
}

const getUserByEmailGlobal = `-- name: GetUserByEmailGlobal :one
SELECT id, created_at, updated_at, company_id, email, password_hash, is_active FROM users
WHERE Email = $1
`

func (q *Queries) GetUserByEmailGlobal(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmailGlobal, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
	)
	return i, err
}

const getUserByIDGlobal = `-- name: GetUserByIDGlobal :one
SELECT id, created_at, updated_at, company_id, email, password_hash, is_active FROM users
WHERE ID = $1
`

func (q *Queries) GetUserByIDGlobal(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByIDGlobal, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
	)
	return i, err
}

const resetUsers = `-- name: ResetUsers :exec
Delete FROM users
`

func (q *Queries) ResetUsers(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetUsers)
	return err
}

const setUserActiveStatus = `-- name: SetUserActiveStatus :exec
UPDATE users
SET Is_Active = $1
WHERE ID = $2
AND Company_ID = $3
`

type SetUserActiveStatusParams struct {
	IsActive  bool
	ID        uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) SetUserActiveStatus(ctx context.Context, arg SetUserActiveStatusParams) error {
	_, err := q.db.ExecContext(ctx, setUserActiveStatus, arg.IsActive, arg.ID, arg.CompanyID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    Email = $1,
    Is_Active = $2
WHERE ID = $3
AND Company_ID = $4
RETURNING id, created_at, updated_at, company_id, email, password_hash, is_active
`

type UpdateUserParams struct {
	Email     string
	IsActive  bool
	ID        uuid.UUID
	CompanyID uuid.UUID
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Email,
		arg.IsActive,
		arg.ID,
		arg.CompanyID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
	)
	return i, err
}
