version: 3

tasks:

  fmt:
    desc: "Format all Go code"
    cmds:
      - go fmt ./...

  vet:
    desc: "Static analysis of Go code"
    cmds:
      - go vet ./...

  test:
    desc: "Run all Go tests with coverage"
    cmds:
      - go test ./... -cover

  tidy:
    desc: "Clean up and sync Go modules"
    cmds:
      - go mod tidy

  clean:
    desc: "Remove caches and build artifacts"
    cmds:
      - go clean -modcache -testcache
      - rm -rf ./bin ./dist || true

  check-all:
    desc: "Run fmt, vet, test, and tidy in sequence"
    cmds:
      - task: fmt
      - task: vet
      - task: test
      - task: tidy
