// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package app

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LoginPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = Layout("Log in • RevProject", LoginContent()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func LoginContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"login-layout\"><section class=\"card\" id=\"auth-card\"><header><h1>Sign in to continue</h1><p class=\"card-subtitle\">Use your company credentials to access RevProject. Sessions persist securely with HTTP-only cookies.</p></header><form hx-post=\"/auth/login\" hx-target=\"#login-message\" hx-swap=\"innerHTML\" hx-indicator=\"#login-indicator\" hx-vals=\"js:{ timezoneOffset: new Date().getTimezoneOffset() }\"><label>Company name <input type=\"text\" name=\"companyName\" class=\"input-field\" autocomplete=\"organization\" required placeholder=\"Acme Corporation\"></label> <label>Email address <input type=\"email\" name=\"email\" class=\"input-field\" autocomplete=\"email\" required placeholder=\"team@company.com\"></label> <label>Password <input type=\"password\" name=\"password\" class=\"input-field\" autocomplete=\"current-password\" required minlength=\"8\" placeholder=\"Enter your password\"></label><div class=\"form-row\"><label class=\"remember-option\"><input type=\"checkbox\" name=\"remember\" value=\"true\"> Remember me</label> <a href=\"/forgot-password\" class=\"form-link\">Forgot password?</a></div><button type=\"submit\">Log in</button><div id=\"login-indicator\" class=\"htmx-indicator\" aria-live=\"polite\" aria-hidden=\"true\"><svg viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><circle cx=\"12\" cy=\"12\" r=\"9\" stroke-opacity=\"0.2\"></circle> <path d=\"M21 12a9 9 0 0 1-9 9\"></path></svg> Authenticating…</div><p id=\"login-message\" class=\"message\" aria-live=\"polite\"></p></form><div class=\"alt-actions\"><span>Just exploring?</span> <a href=\"/request-access\">Request company access</a></div></section></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
