// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/JonMunkholm/RevProject1/app/layout"

func LoginPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = layout.LayoutWithAssets("Sign In • RevProject", []string{"/assets/css/auth.css", "/assets/css/login.css"}, LoginContent()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func LoginContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<main class=\"auth-page\" role=\"main\"><section class=\"auth-card\" id=\"auth-card\"><header class=\"auth-header\"><h1>Sign in</h1><p>New to RevProject? <a href=\"/register\">Create an account</a></p></header><div id=\"login-message\" class=\"auth-feedback\" aria-live=\"polite\" role=\"status\"></div><form class=\"auth-form\" hx-post=\"/auth/login\" hx-target=\"#login-message\" hx-swap=\"innerHTML\" hx-indicator=\"#login-indicator\" hx-vals=\"js:{ timezoneOffset: new Date().getTimezoneOffset() }\" novalidate><div class=\"form-field\"><label for=\"login-email\">Email address</label> <input id=\"login-email\" type=\"email\" name=\"email\" autocomplete=\"email\" required placeholder=\"name@company.com\"></div><div class=\"form-field\"><label for=\"login-password\">Password</label> <input id=\"login-password\" type=\"password\" name=\"password\" autocomplete=\"current-password\" required minlength=\"8\" placeholder=\"Enter your password\"></div><button type=\"submit\" class=\"primary-button\">Sign in</button><div id=\"login-indicator\" class=\"auth-indicator\" aria-live=\"polite\" aria-hidden=\"true\"><span class=\"spinner\" aria-hidden=\"true\"></span> <span>Checking credentials…</span></div></form><div class=\"auth-separator\" role=\"presentation\"><span>Or with</span></div><button type=\"button\" class=\"sso-button\" name=\"sso\" value=\"true\">Continue with Single Sign-On</button><div class=\"auth-links\"><a href=\"/forgot-password\">Forgot password?</a> <span aria-hidden=\"true\">·</span> <a href=\"/support\">Support</a> <span aria-hidden=\"true\">·</span> <a href=\"/legal/privacy\">Privacy</a></div></section></main>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
